# Generated by Django 3.2.5 on 2021-07-29 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipieCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipiecategorie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('one_word', models.CharField(max_length=30)),
                ('servig_size', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('vitaminA', models.IntegerField()),
                ('time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('main_image', models.ImageField(upload_to='main_images')),
                ('image_first', models.ImageField(upload_to='image1')),
                ('image_second', models.ImageField(upload_to='image2')),
                ('image_third', models.ImageField(upload_to='image3')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipiecategorie')),
            ],
        ),
    ]
