# Generated by Django 3.2.5 on 2021-07-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='description',
            field=models.TextField(),
        ),
    ]
